### PR TITLE
Align allocWorkBufffers to 32 bytes

### PR DESCRIPTION
**Pull request by jcberentsen**
Possible fix for #53

### CODE REVIEW

**Comment by jcberentsen** [comment]
This particularly fixes the original #53 for me. Perhaps there are other places that should have the same alignment?

**Comment by newhoggy** [comment]
I'm inclined to think that if this makes works for you then that's all that is needed.  The alignment is only needed when passed to C functions that make use of the SIMD instructions that use the alignment.

**Comment by newhoggy** [comment]
Can you check if the fix in this PR works?

https://github.com/haskell-works/hw-json-simd/pull/58

I prefer this version since the `32` isn't repeated reducing the opportunity for error.

**Comment by jcberentsen** [comment]
Testing #58 works good on my end. I'll close this PR
Thank you for taking the time on this issue!

My usecase went from 3s down to 0.58s by computing the SIMD cursor!
The hw-json project is amazing!

**Pull request closed without merging**
